apiVersion: apps/v1
kind: Deployment
metadata:
  name: dandelion-api
  labels:
    app: dandelion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dandelion-api
  template:
    metadata:
      labels:
        app: dandelion-api
    spec:
      containers:
        - name: dandelion-api
          image: dandelion-api:latest
          imagePullPolicy: Never  # car tu utilises lâ€™image locale
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5001"
            - name: S3_ENDPOINT_URL
              value: "http://minio:9000"
            - name: S3_ACCESS_KEY
              value: "minioadmin"
            - name: S3_SECRET_KEY
              value: "minioadmin"